services:
  ugc:
    build: .
    container_name: ugc
    restart: always
    env_file:
      - "./.env"
    expose:
      - 8000
    volumes:
      - ${KAFKA_SSL_CAFILE}:/etc/CA.pem
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: ugc

  nginx:
    build: ./nginx
    volumes:
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - ugc
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: nginx

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/node1:/etc/clickhouse-server
      - ./etl/clickhouse/config:/etc/clickhouse-server/config.d
      - ${KAFKA_SSL_CAFILE}:/etc/CA.pem
    env_file:
      - .env
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./data/node2:/etc/clickhouse-server
      - ./etl/clickhouse/config:/etc/clickhouse-server/config.d
      - ${KAFKA_SSL_CAFILE}:/etc/CA.pem
    env_file:
      - .env
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./data/node3:/etc/clickhouse-server
      - ./etl/clickhouse/config:/etc/clickhouse-server/config.d
      - ${KAFKA_SSL_CAFILE}:/etc/CA.pem
    env_file:
      - .env
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./data/node4:/etc/clickhouse-server
      - ./etl/clickhouse/config:/etc/clickhouse-server/config.d
      - ${KAFKA_SSL_CAFILE}:/etc/CA.pem
    env_file:
      - .env
    depends_on:
      - zookeeper

  etl-migrations:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: etl
    env_file:
      - .env
    depends_on:
      - clickhouse-node1
