version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:22
    restart: on-failure
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./etl/clickhouse/config:/etc/clickhouse-server/config.d
      - ./etl/clickhouse/CA.pem:/usr/src/app/CA.pem
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    env_file:
      - ch.env
