@startuml
!theme materia
skinparam componentStyle uml1
skinparam backgroundColor MOTIVATION

title [ARCH]: TO BE

agent Client
cloud "NGINX" as server
Client <--> server: Клиентские запросы
agent Analyst
Analyst <--> server: Аналитические запросы

node Content {
    database Movies
    database SearchMovies
    frame Admin_panel {
        database Staff
        component Django_Admin
        component Django_API
        Django_Admin <-> Staff: Данные персонала
    }
    frame ETL {
        database State
        file Extractor
        file Transformer
        file Loader
        State <-- Extractor: Сырые данные
        State <--> Transformer: Обработка данных
        State --> Loader: Подготовленные данные
    }
    frame Async_API {
        component Search_API
        database Cache
        Search_API <-> Cache: Кэширование
    }
    Movies --> Extractor: Выгрузка сырых данных
    Django_Admin <--> Movies: Работа с контентом
    Django_API <--> Movies: Запросы контента
    Loader --> SearchMovies: Загрузка подготовденных данных
    Search_API <--> SearchMovies: Поиск контента
}

server <--> Django_API: Запросы фильмов/жанров/персон по UUID
server <--> Search_API: Поисковые запросы
server <--> Django_Admin: Добавление/удаление/редактирование контента персоналом

node Auth {
    component Auth_API
    component OAuth2.0_API
    database Users
    Auth_API <--> Users
    OAuth2.0_API <--> Users: Работа с пользовательскими данными
}

server <--> Auth_API: Авторизация с помощью пользовательских данных
server <--> OAuth2.0_API: Авторизация через соц.сети

node UGC {
    frame OLTP {
        component UGC_Api
        queue Kafka
        UGC_Api -> Kafka: Передача событий
    }
    frame OLAP {
        database ClickHouse_Cluster {
            file ClickHouse_ETL
            database Shard_1
            database Shard_2
            database Shard_n
            ClickHouse_ETL --> Shard_1: Подготовленные данные
            ClickHouse_ETL --> Shard_2: Подготовленные данные
            ClickHouse_ETL --> Shard_n
        }
    }
    Kafka --> ClickHouse_ETL: Сырые события
}
server <--> UGC_Api: Работа с событиями
@enduml
