name: Python application

on:
  push:
    branches: [ master, dev, 67-24-ci ]
  pull_request:
    branches: [ master, dev, 67-24-ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install

    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.16.1
